[package]
name = "ClientRust"
version = "0.1.0"
authors = ["qwertz"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libmath = "0.2.1"
aes-gcm = "0.5.0"
json = "0.12.4"
rand = "0.7.3"
generic-array = "0.13.2"